--Written by Keegan Sweet

/* We're going to model the customer's database structure using Oracle's
sample data*/

--Create new schema for CompanyA. Password redacted.

CREATE USER COMPANYA IDENTIFIED BY --Password; 
GRANT CONNECT, RESOURCE TO COMPANYA;
GRANT CREATE VIEW TO COMPANYA;

--Restart SQL

--Create tablespace quota for CompanyA

ALTER USER CompanyA QUOTA UNLIMITED ON USERS;
SET DEFINE OFF;

-- Sales Regions:

SELECT DISTINCT JOB_TITLE FROM HR.EMP_DETAILS_VIEW;

SELECT * FROM HR.EMP_DETAILS_VIEW WHERE JOB_TITLE='Sales Manager' OR JOB_TITLE='President';

SELECT * FROM HR.EMP_DETAILS_VIEW WHERE JOB_TITLE='Sales Representative';

SELECT * FROM HR.EMP_DETAILS_VIEW WHERE EMPLOYEE_ID=100;

SELECT OE.ACCOUNT_MANAGERS.*, SH.COUNTRIES.COUNTRY_NAME 
FROM OE.ACCOUNT_MANAGERS 
JOIN SH.COUNTRIES ON OE.ACCOUNT_MANAGERS.COUNTRY=SH.COUNTRIES.COUNTRY_ISO_CODE 
ORDER BY OE.ACCOUNT_MANAGERS.ACCT_MGR ASC;

--States:

SELECT COUNTRY_ID, COUNTRY_NAME FROM SH.COUNTRIES;
SELECT DISTINCT 
CUST_STATE_PROVINCE, 
CUST_STATE_PROVINCE_ID 
FROM SH.CUSTOMERS 
WHERE CUST_STATE_PROVINCE LIKE '__' ORDER BY CUST_STATE_PROVINCE;

SELECT * FROM SH.CUSTOMERS WHERE CUST_STATE_PROVINCE_ID=52604;

SELECT DISTINCT CUST_CITY FROM SH.CUSTOMERS WHERE CUST_STATE_PROVINCE_ID=52604;
--All 2-letter provinces are US States. Georgia is incorrectly labeled as, "GE".

--Display customer countries:

SELECT DISTINCT COUNTRY_ID FROM SH.CUSTOMERS;
SELECT DISTINCT CUSTOMERS.COUNTRY_ID, COUNTRIES.COUNTRY_NAME
FROM SH.CUSTOMERS
JOIN SH.COUNTRIES ON CUSTOMERS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
ORDER BY COUNTRY_ID;

/* I need to create 2 regions tables: one that shows state/province to divide 
the US regions, and another that retains country id integrity*/

CREATE TABLE COMPANYA.STATE_PROVINCE(
REGIONID NUMBER,
REGION VARCHAR2(50),
COUNTRYID NUMBER,
COUNTRY VARCHAR2(50),
"STATE" VARCHAR2(50);

INSERT INTO COMPANYA.STATE_PROVINCE(REGIONID, REGION, COUNTRYID, COUNTRY, "STATE")
SELECT DISTINCT 145, 'US WEST + MARYLAND', COUNTRY_ID, 'United States of America', CUST_STATE_PROVINCE
FROM SH.CUSTOMERS
WHERE CUST_STATE_PROVINCE IN
('AK','AR','CA','CO','HI','IA','IL','IN','KS','LA','MD','MI','MN','MO','MT','ND',
'NE','NM','NV','OK','OR','SD','TX','UT','WA','WI','WY')
ORDER BY CUST_STATE_PROVINCE;

INSERT INTO COMPANYA.STATE_PROVINCE(REGIONID, REGION, COUNTRYID, COUNTRY, "STATE")
SELECT DISTINCT 149, 'US EAST', COUNTRY_ID, 'United States of America', CUST_STATE_PROVINCE
FROM SH.CUSTOMERS
WHERE CUST_STATE_PROVINCE NOT IN
('AK','AR','CA','CO','HI','IA','IL','IN','KS','LA','MD','MI','MN','MO','MT','ND',
'NE','NM','NV','OK','OR','SD','TX','UT','WA','WI','WY')
AND LENGTH(CUST_STATE_PROVINCE)=2
ORDER BY CUST_STATE_PROVINCE;

INSERT INTO COMPANYA.STATE_PROVINCE(REGIONID, REGION, COUNTRYID, COUNTRY, "STATE")
SELECT DISTINCT 
147, 
'EUROPE & CANADA',
COUNTRIES.COUNTRY_ID, 
COUNTRIES.COUNTRY_NAME, 
CUSTOMERS.CUST_STATE_PROVINCE
FROM SH.COUNTRIES
JOIN SH.CUSTOMERS ON COUNTRIES.COUNTRY_ID=CUSTOMERS.COUNTRY_ID
WHERE COUNTRIES.COUNTRY_NAME IN
('Italy','Canada','Germany','Denmark','Spain','France','Poland','Turkey','United Kingdom')
ORDER BY COUNTRIES.COUNTRY_NAME;

INSERT INTO COMPANYA.STATE_PROVINCE(REGIONID, REGION, COUNTRYID, COUNTRY, "STATE")
SELECT DISTINCT 
148, 
'ASIA',
COUNTRIES.COUNTRY_ID, 
COUNTRIES.COUNTRY_NAME, 
CUSTOMERS.CUST_STATE_PROVINCE
FROM SH.COUNTRIES
JOIN SH.CUSTOMERS ON COUNTRIES.COUNTRY_ID=CUSTOMERS.COUNTRY_ID
WHERE COUNTRIES.COUNTRY_NAME IN
('Australia','Japan','New Zealand','Saudi Arabia')
ORDER BY COUNTRIES.COUNTRY_NAME;

INSERT INTO COMPANYA.STATE_PROVINCE(REGIONID, REGION, COUNTRYID, COUNTRY, "STATE")
SELECT DISTINCT 
146, 
'Africa & LATAM', 
COUNTRIES.COUNTRY_ID, 
COUNTRIES.COUNTRY_NAME,
CUSTOMERS.CUST_STATE_PROVINCE
FROM SH.COUNTRIES
JOIN SH.CUSTOMERS ON COUNTRIES.COUNTRY_ID=CUSTOMERS.COUNTRY_ID
WHERE COUNTRIES.COUNTRY_NAME IN
('Argentina','Brazil','South Africa')
ORDER BY COUNTRIES.COUNTRY_NAME;

--Create unique COUNTRYID table:

CREATE TABLE COMPANYA.COUNTRY_REGION AS
SELECT DISTINCT REGIONID, REGION, COUNTRYID, COUNTRY
FROM COMPANYA.STATE_PROVINCE
WHERE REGION NOT IN('US WEST + MARYLAND','US EAST');

SELECT DISTINCT REGIONID, REGION, COUNTRYID, COUNTRY
FROM COMPANYA.STATE_PROVINCE
WHERE REGION NOT IN('US WEST + MARYLAND','US EAST');

--Sales Managers

CREATE TABLE COMPANYA.SALESMGRS(
EMPID NUMBER, 
MGRID NUMBER, 
FNAME VARCHAR2(50), 
LNAME VARCHAR2(50), 
USERNAME VARCHAR2(50));
ALTER TABLE COMPANYA.SALESMGRS MODIFY EMPID NUMBER NOT NULL;

INSERT INTO COMPANYA.SALESMGRS(EMPID, MGRID, FNAME, LNAME) 
SELECT DISTINCT EMPLOYEE_ID, MANAGER_ID, FIRST_NAME, LAST_NAME 
FROM HR.EMP_DETAILS_VIEW 
WHERE JOB_TITLE='Sales Manager' OR JOB_TITLE='President' 
ORDER BY EMPLOYEE_ID;

ALTER TABLE COMPANYA.SALESMGRS ADD REGION VARCHAR2(50);
UPDATE COMPANYA.SALESMGRS 
SET SALESMGRS.REGION=(
SELECT DISTINCT STATE_PROVINCE.REGION 
FROM COMPANYA.STATE_PROVINCE 
WHERE STATE_PROVINCE.REGIONID = SALESMGRS.EMPID
);

SELECT * FROM COMPANYA.SALESMGRS;
UPDATE COMPANYA.SALESMGRS SET USERNAME='SKING@COMPANYA.COM' WHERE EMPID=100;
UPDATE COMPANYA.SALESMGRS SET USERNAME='JRUSSELL@COMPANYA.COM' WHERE EMPID=145;
UPDATE COMPANYA.SALESMGRS SET USERNAME='KPARTNERS@COMPANYA.COM' WHERE EMPID=146;
UPDATE COMPANYA.SALESMGRS SET USERNAME='AERRAZURIZ@COMPANYA.COM' WHERE EMPID=147;
UPDATE COMPANYA.SALESMGRS SET USERNAME='GCAMBRAULT@COMPANYA.COM' WHERE EMPID=148;
UPDATE COMPANYA.SALESMGRS SET USERNAME='EZLOTKEY@COMPANYA.COM' WHERE EMPID=149;

--Sales Reps

CREATE TABLE COMPANYA.SALESREPS AS SELECT * FROM COMPANYA.SALESMGRS;
TRUNCATE TABLE COMPANYA.SALESREPS;

SELECT * FROM COMPANYA.SALESMGRS;

INSERT INTO COMPANYA.SALESREPS (
EMPID, 
MGRID, 
FNAME, 
LNAME
) 
SELECT DISTINCT 
EMPLOYEE_ID, 
MANAGER_ID, 
FIRST_NAME, 
LAST_NAME 
FROM HR.EMP_DETAILS_VIEW 
WHERE JOB_TITLE='Sales Representative' 
ORDER BY EMPLOYEE_ID;

UPDATE COMPANYA.SALESREPS 
SET REGION=(
SELECT DISTINCT STATE_PROVINCE.REGION 
FROM COMPANYA.STATE_PROVINCE 
WHERE STATE_PROVINCE.REGIONID = SALESREPS.MGRID
);

SELECT * FROM COMPANYA.SALESREPS;

--Many records. Create GTT for sales dept email structure.
CREATE GLOBAL TEMPORARY TABLE COMPANYA.USERNAME ON COMMIT PRESERVE ROWS AS
SELECT EMPID, 
       FNAME, 
       LNAME, 
       SUBSTR(FNAME, 1, 1) || LNAME || '@COMPANYA.COM' AS USERNAME
FROM COMPANYA.SALESREPS ORDER BY EMPID;
SELECT * FROM COMPANYA.USERNAME;

UPDATE COMPANYA.SALESREPS
SET COMPANYA.SALESREPS.USERNAME=(SELECT COMPANYA.USERNAME.USERNAME
                    FROM COMPANYA.USERNAME
                    WHERE COMPANYA.USERNAME.EMPID=COMPANYA.SALESREPS.EMPID);

--FactSales

SELECT COUNT(*) FROM SH.SALES;
SELECT DISTINCT COUNT(*) FROM SH.SALES;
--All transactions are unique, but are not defined by an ID column

CREATE TABLE COMPANYA.FACTSALES(
SALESID NUMBER PRIMARY KEY,
SALESDATEID DATE, 
SALESAMT NUMBER(10,2),
CUSTID NUMBER NOT NULL, 
SHIPDATEID DATE,
REGIONID NUMBER
);

--Creating a sequence to generate RowID column for SALESID

CREATE SEQUENCE COMPANYA.SALESIDSQC
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER COMPANYA.SALESIDTRG
BEFORE INSERT ON COMPANYA.FACTSALES
FOR EACH ROW
BEGIN
  SELECT COMPANYA.SALESIDSQC.NEXTVAL INTO :NEW.SALESID FROM dual;
END;
/

INSERT INTO COMPANYA.FACTSALES(SALESDATEID, SALESAMT, CUSTID, SHIPDATEID, REGIONID) 

SELECT DISTINCT 
SALES.TIME_ID,
SALES.AMOUNT_SOLD,
SALES.CUST_ID,
SALES.TIME_ID+3,
STATE_PROVINCE.REGIONID
FROM SH.SALES
JOIN SH.CUSTOMERS ON SALES.CUST_ID=CUSTOMERS.CUST_ID
JOIN COMPANYA.STATE_PROVINCE ON STATE_PROVINCE."STATE"=CUSTOMERS.CUST_STATE_PROVINCE
ORDER BY TIME_ID;
    
--Date

CREATE TABLE COMPANYA."DATE" (
DATEID DATE NOT NULL, 
"MONTH" NUMBER(2,0), 
WEEK NUMBER(2,0), 
"YEAR" NUMBER(4,0)
);

INSERT INTO COMPANYA."DATE"(DATEID, "MONTH", WEEK, "YEAR") 
SELECT DISTINCT
TIME_ID,
CALENDAR_MONTH_NUMBER,
CALENDAR_WEEK_NUMBER,
CALENDAR_YEAR

FROM SH.TIMES ORDER BY TIME_ID;

-- Weekly returns


/* We neeed to get sales by region by week, I'll create some
intermediate views */ 

--Regional Sales

CREATE VIEW COMPANYA.USWEST_TRANSACTIONS AS
SELECT DISTINCT
SALES.PROD_ID,
SALES.CUST_ID,
SALES.TIME_ID,
SALES.QUANTITY_SOLD,
SALES.AMOUNT_SOLD
FROM SH.SALES
JOIN SH.CUSTOMERS ON SALES.CUST_ID=CUSTOMERS.CUST_ID
JOIN COMPANYA.STATE_PROVINCE ON CUSTOMERS.CUST_STATE_PROVINCE=STATE_PROVINCE."STATE"
WHERE STATE_PROVINCE."STATE" IN(
'AK','AR','CA','CO','HI','IA','IL','IN','KS','LA','MD','MI','MN','MO','MT','ND','NE','NM',
'NV','OK','OR','SD','TX','UT','WA','WI','WY')
ORDER BY SALES.TIME_ID;


CREATE VIEW COMPANYA.USWEST_WEEKLYRETURNS AS
SELECT 
  "DATE"."YEAR",
  "DATE".WEEK,
  SUM(USWEST_TRANSACTIONS.AMOUNT_SOLD) AS WK_RETURN,
  145 AS REGIONID
FROM 
USWEST_TRANSACTIONS
JOIN 
  COMPANYA."DATE" ON USWEST_TRANSACTIONS.TIME_ID = "DATE".DATEID
GROUP BY 
  "DATE"."YEAR", 
  "DATE".WEEK
ORDER BY 
  "DATE"."YEAR", 
  "DATE".WEEK;


CREATE VIEW COMPANYA.USEAST_TRANSACTIONS AS
SELECT DISTINCT
SALES.PROD_ID,
SALES.CUST_ID,
SALES.TIME_ID,
SALES.QUANTITY_SOLD,
SALES.AMOUNT_SOLD
FROM SH.SALES
JOIN SH.CUSTOMERS ON SALES.CUST_ID=CUSTOMERS.CUST_ID
JOIN COMPANYA.STATE_PROVINCE ON CUSTOMERS.CUST_STATE_PROVINCE=STATE_PROVINCE."STATE"
WHERE STATE_PROVINCE."STATE" NOT IN(
'AK','AR','CA','CO','HI','IA','IL','IN','KS','LA','MD','MI','MN','MO','MT','ND','NE',
'NM','NV','OK','OR','SD','TX','UT','WA','WI','WY')
AND LENGTH(CUST_STATE_PROVINCE)=2
ORDER BY SALES.TIME_ID;

CREATE VIEW COMPANYA.USEAST_WEEKLYRETURNS AS
SELECT 
  "DATE"."YEAR",
  "DATE".WEEK,
  SUM(USEAST_TRANSACTIONS.AMOUNT_SOLD) AS WK_RETURN,
  149 AS REGIONID
FROM 
USEAST_TRANSACTIONS
JOIN 
  COMPANYA."DATE" ON USEAST_TRANSACTIONS.TIME_ID = "DATE".DATEID
GROUP BY 
  "DATE"."YEAR", 
  "DATE".WEEK
ORDER BY 
  "DATE"."YEAR", 
  "DATE".WEEK;

CREATE VIEW COMPANYA.EU_CANADA_TRANSACTIONS AS
SELECT DISTINCT
SALES.PROD_ID,
SALES.CUST_ID,
SALES.TIME_ID,
SALES.QUANTITY_SOLD,
SALES.AMOUNT_SOLD
FROM SH.SALES
JOIN SH.CUSTOMERS ON SALES.CUST_ID=CUSTOMERS.CUST_ID
JOIN COMPANYA.COUNTRY_REGION ON CUSTOMERS.COUNTRY_ID=COUNTRY_REGION.COUNTRYID
WHERE COUNTRY_REGION.COUNTRY IN
('Italy','Canada','Germany','Denmark','Spain','France','Poland','Turkey','United Kingdom')
ORDER BY SALES.TIME_ID;

CREATE VIEW COMPANYA.EU_CANADA_WEEKLYRETURNS AS
SELECT 
  "DATE"."YEAR",
  "DATE".WEEK,
  SUM(EU_CANADA_TRANSACTIONS.AMOUNT_SOLD) AS WK_RETURN,
  147 AS REGIONID
FROM 
EU_CANADA_TRANSACTIONS
JOIN 
  COMPANYA."DATE" ON EU_CANADA_TRANSACTIONS.TIME_ID = "DATE".DATEID
GROUP BY 
  "DATE"."YEAR", 
  "DATE".WEEK
ORDER BY 
  "DATE"."YEAR", 
  "DATE".WEEK;

CREATE VIEW COMPANYA.ASIA_TRANSACTIONS AS
SELECT DISTINCT
SALES.PROD_ID,
SALES.CUST_ID,
SALES.TIME_ID,
SALES.QUANTITY_SOLD,
SALES.AMOUNT_SOLD
FROM SH.SALES
JOIN SH.CUSTOMERS ON SALES.CUST_ID=CUSTOMERS.CUST_ID
JOIN COMPANYA.COUNTRY_REGION ON CUSTOMERS.COUNTRY_ID=COUNTRY_REGION.COUNTRYID
WHERE COUNTRY_REGION.COUNTRY IN
('Australia','Japan','New Zealand','Saudi Arabia')
ORDER BY SALES.TIME_ID;

CREATE VIEW COMPANYA.ASIA_WEEKLYRETURNS AS
SELECT 
  "DATE"."YEAR",
  "DATE".WEEK,
  SUM(ASIA_TRANSACTIONS.AMOUNT_SOLD) AS WK_RETURN,
  148 AS REGIONID
FROM 
ASIA_TRANSACTIONS
JOIN 
  COMPANYA."DATE" ON ASIA_TRANSACTIONS.TIME_ID = "DATE".DATEID
GROUP BY 
  "DATE"."YEAR", 
  "DATE".WEEK
ORDER BY 
  "DATE"."YEAR", 
  "DATE".WEEK;

CREATE VIEW COMPANYA.AFRICA_LATAM_TRANSACTIONS AS
SELECT DISTINCT
SALES.PROD_ID,
SALES.CUST_ID,
SALES.TIME_ID,
SALES.QUANTITY_SOLD,
SALES.AMOUNT_SOLD
FROM SH.SALES
JOIN SH.CUSTOMERS ON SALES.CUST_ID=CUSTOMERS.CUST_ID
JOIN COMPANYA.COUNTRY_REGION ON CUSTOMERS.COUNTRY_ID=COUNTRY_REGION.COUNTRYID
WHERE COUNTRY_REGION.COUNTRY IN
('Argentina','Brazil','South Africa')
ORDER BY SALES.TIME_ID;

CREATE VIEW COMPANYA.AFRICA_LATAM_WEEKLYRETURNS AS
SELECT 
  "DATE"."YEAR",
  "DATE".WEEK,
  SUM(AFRICA_LATAM_TRANSACTIONS.AMOUNT_SOLD) AS WK_RETURN,
  146 AS REGIONID
FROM 
AFRICA_LATAM_TRANSACTIONS
JOIN 
  COMPANYA."DATE" ON AFRICA_LATAM_TRANSACTIONS.TIME_ID = "DATE".DATEID
GROUP BY 
  "DATE"."YEAR", 
  "DATE".WEEK
ORDER BY 
  "DATE"."YEAR", 
  "DATE".WEEK;

--Regional sales by week:

CREATE TABLE COMPANYA.WEEKLY_RETURNS AS
SELECT * FROM COMPANYA.ASIA_WEEKLYSALES;
TRUNCATE TABLE COMPANYA.WEEKLY_RETURNS;

INSERT INTO COMPANYA.WEEKLY_RETURNS
SELECT*FROM COMPANYA.USWEST_WEEKLYSALES;

INSERT INTO COMPANYA.WEEKLY_RETURNS
SELECT*FROM COMPANYA.AFRICA_LATAM_WEEKLYSALES;

INSERT INTO COMPANYA.WEEKLY_RETURNS
SELECT*FROM COMPANYA.EU_CANADA_WEEKLYSALES;

INSERT INTO COMPANYA.WEEKLY_RETURNS
SELECT*FROM COMPANYA.ASIA_WEEKLYSALES;

INSERT INTO COMPANYA.WEEKLY_RETURNS
SELECT*FROM COMPANYA.USEAST_WEEKLYSALES;

--Tsrgets

/* We don't know anything about the Company's monthly sales targets, so I'll simply
substitute the inflation rate for the variables. Data ends at 12/24/01. We'll simply
adapt the targets to Jan 2002 */

CREATE TABLE COMPANYA.JAN02_REGION_TARGETS(
TARGETID NUMBER NOT NULL,
"TARGET" NUMBER(10,2),
END_DATE DATE,
REGIONID NUMBER NOT NULL);

INSERT INTO COMPANYA.JAN02_REGION_TARGETS(TARGETID, "TARGET", END_DATE, REGIONID)
SELECT 145012001, SUM(AMOUNT_SOLD)*1.0315, TO_DATE('31-JAN-2002', 'DD-MON-YYYY'), 145
FROM COMPANYA.USWEST_TRANSACTIONS
WHERE TO_CHAR(TIME_ID,'MON-YY') = 'DEC-01';

INSERT INTO COMPANYA.JAN02_REGION_TARGETS(TARGETID, "TARGET", END_DATE, REGIONID)
SELECT 146012001, SUM(AMOUNT_SOLD)*1.0315, TO_DATE('31-JAN-2002', 'DD-MON-YYYY'), 146
FROM COMPANYA.AFRICA_LATAM_TRANSACTIONS
WHERE TO_CHAR(TIME_ID,'MON-YY') = 'DEC-01';

INSERT INTO COMPANYA.JAN02_REGION_TARGETS(TARGETID, "TARGET", END_DATE, REGIONID)
SELECT 147012001, SUM(AMOUNT_SOLD)*1.0315, TO_DATE('31-JAN-2002', 'DD-MON-YYYY'), 147
FROM COMPANYA.EU_CANADA_TRANSACTIONS
WHERE TO_CHAR(TIME_ID,'MON-YY') = 'DEC-01';

INSERT INTO COMPANYA.JAN02_REGION_TARGETS(TARGETID, "TARGET", END_DATE, REGIONID)
SELECT 148012001, SUM(AMOUNT_SOLD)*1.0315, TO_DATE('31-JAN-2002', 'DD-MON-YYYY'), 148
FROM COMPANYA.ASIA_TRANSACTIONS
WHERE TO_CHAR(TIME_ID,'MON-YY') = 'DEC-01';

INSERT INTO COMPANYA.JAN02_REGION_TARGETS(TARGETID, "TARGET", END_DATE, REGIONID)
SELECT 149012001, SUM(AMOUNT_SOLD)*1.0315, TO_DATE('31-JAN-2002', 'DD-MON-YYYY'), 149
FROM COMPANYA.USEAST_TRANSACTIONS
WHERE TO_CHAR(TIME_ID,'MON-YY') = 'DEC-01';

COMMIT;